
function noteData() {

    return `   <div id="notsBox">
            <div id="addnots">
                <h1>Add Nots</h1>
                <select>
                    <option value="null">------</option>

                    <optgroup label="More Numbers">

                        <option value="2">1</option>
                        <option value="3">2</option>


                    </optgroup>
                    <optgroup label="More Numbers Part 2">
                        <option value="">3</option>
                        <option value="">4</option>
                        <option value="">5</option>
                    </optgroup>

                    <optgroup label="Some Numbers">

                        <option value="1">6</option>
                        <option value="4">7</option>
                    </optgroup>

                </select>
                <textarea name="" id="" cols="30" rows="4"></textarea>
                <button>Add Nots</button>
            </div>

            <div id="showNots">
                <h1>Show Nots</h1>
                <select>
                    <option value="null">------</option>

                    <optgroup label="More Numbers">

                        <option value="2">1</option>
                        <option value="3">2</option>


                    </optgroup>
                    <optgroup label="More Numbers Part 2">
                        <option value="">3</option>
                        <option value="">4</option>
                        <option value="">5</option>
                    </optgroup>

                    <optgroup label="Some Numbers">

                        <option value="1">6</option>
                        <option value="4">7</option>
                    </optgroup>

                </select>

                <button>Show Nots</button>
            </div>
        </div>`


}


export default noteData




