
function navbar2() {

    return `   <div id="navbar">
        <h3><a href="/UNIT-03/week14/day02/assignment/FoodAppI/index.html">Home</a></h3>

        <div class="options">
            <h3><a href="/UNIT-03/week14/day02/assignment/FoodAppI/ReceipeOfTheDay.html">Receipe Of The Day</a></h3>
            <h3><a href="/UNIT-03/week14/day02/assignment/FoodAppI/LatestReceipe.html">Latest Receipe</a></h3>
        </div>
    </div>
    <div id="data"> </div>`


}


export default navbar2




